name: flibusta
description: Mobile application

version: 0.5.6+34

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1

  utopic_tor_onion_proxy: ^0.2.2

  flutter_typeahead: ^1.8.7
  mask_text_input_formatter: ^1.0.7

  flutter_secure_storage: ^3.3.3
  shared_preferences: ^0.5.8
  flutter_local_notifications: ^1.4.4+2

  url_launcher: ^5.5.0

  font_awesome_flutter: ^8.8.1
  eva_icons_flutter: ^2.0.1

  flutter_bloc: ^6.0.1
  bloc: ^6.0.1
  rxdart: ^0.24.1
  equatable: ^1.2.3
  provider: ^4.3.1

  path_provider: ^1.6.11
  utopic_open_file: ^1.0.0

  html: ^0.14.0+3
  permission_handler: ^5.0.1+1
  
  flutter_slidable: ^0.5.5
  shimmer: ^1.1.1
  avatar_glow: ^1.2.0
  flutter_staggered_animations: ^0.1.2
  launch_review: ^2.0.0
  package_info: ^0.4.1
  flare_flutter: ^2.0.5
  utopic_toast: ^0.1.3
  
  connectivity: ^0.4.9
  data_connection_checker: ^0.3.4

  share: ^0.6.4+3
  
  flutter_svg: ^0.17.4
  
  json_annotation: ^3.0.1
  intl: ^0.16.1

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/Logo.png
    - assets/img/utopic_narwhal.png
    - assets/img/4pda_logo.svg
    - assets/img/tor_logo.svg
    - assets/img/onion_services.svg
    - assets/animations/empty_state.flr
    - assets/animations/books_placeholder.flr
    - assets/animations/long_tap.flr

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
