name: flibusta
description: Mobile application

version: 0.3.5+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.9

  flutter_typeahead: ^1.8.0
  mask_text_input_formatter: ^1.0.6

  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^0.5.6+3

  url_launcher: ^5.4.2

  font_awesome_flutter: ^8.7.0
  eva_icons_flutter: ^2.0.0

  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  rxdart: ^0.23.1
  easy_debounce: ^1.0.1
  equatable: ^1.1.1
  provider: ^4.0.4

  path_provider: ^1.6.5
  open_file: ^3.0.1

  html: ^0.14.0+3
  permission_handler: ^4.4.0+hotfix.2
  
  flutter_slidable: ^0.5.4
  oktoast: ^2.3.1+1
  shimmer: ^1.1.0
  avatar_glow: ^1.1.0
  flutter_staggered_animations: ^0.1.2
  launch_review: ^2.0.0
  package_info: ^0.4.0+16
  flare_flutter: ^2.0.1

  share: ^0.6.3+6
  connectivity: ^0.4.8+2
  data_connection_checker: ^0.3.4
  
  intro_slider: ^2.2.9
  flutter_svg: ^0.17.3+1
  
  json_annotation: ^3.0.1
  intl: ^0.16.0

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true

  assets:
    - assets/img/Logo.png
    - assets/img/bg-header.png
    - assets/img/flibusta_logo.png
    - assets/img/utopic_narwhal.png
    - assets/img/4pda_logo.svg
    - assets/animations/empty_state.flr
    - assets/animations/floating_document.flr
    - assets/animations/questions.flr
    - assets/animations/like.flr
    - assets/animations/roskomnadzor.flr

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
